### ISSUE TITLE
Cannot `ls` with FreeBSD NFS Client

### ISSUE THREAD

**Issue by windkit** [leo-project/leo_gateway#27]
### Observation
```
$ ls -l /mnt/leofs
total 0
ls: /mnt/leofs: Permission denied
```

#### `fsstat` cannot get disk usage
 - This is because the `leo_filefile_get_mount_path` fails when relative path is used for object container (e.g. ./avs)

##### Solution
  - [Related Pull Request](https://github.com/leo-project/leo_commons/pull/5)

#### FreeBSD uses `READDIR` by default
  - leo_gateway only handles `READDIRPLUS` but not `READDIR`
  - [Related Section in RFC 1813](https://tools.ietf.org/html/rfc1813#section-3.3.16)

##### Solution
  - Implement `READDIRPLUS` in leo_gateway
  - use `-o rdirplus` mount options
   - [FreeBSD mount_nfs Documentation] (https://www.freebsd.org/cgi/man.cgi?mount_nfs(8))

**Comment by mocchira** [comment]
@windkit 
Thanks. I've merged your PR.
Since the solution for READDIR should be described on the document,
Please write a document for FreeBSD users at http://leo-project.net/leofs/docs/configuration/configuration_6.html,
and PR to leofs_docs.

After finishing to review and merge the doc into mainline, 
I'll close this.

**Comment by windkit** [comment]
Implementing READDIR seems straight-forward with the code for READDIRPLUS, I will create a PR for that afterwards.

As mentioned, I will confirm the max write size for FreeBSD case.
